In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler  # Optional
from sklearn.svm import OneClassSVM

In [3]:
# "normal_documents" ids DataFrame with topic features
normal_documents = pd.read_csv('/home/nazma/NLP-based-Email-Content-Digital-Forensic-using-ML-model-and-Explainable-AI/topic_features_final_labeled.csv')
normal_documents

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False
1,1,1,0,0,0,2,0,0,0,0,0,22,0,1,1,0,0,False
2,2,2,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,False
3,3,3,2,1,0,2,1,4,3,0,1,3,1,0,0,1,1,False
4,4,4,1,17,1,40,7,4,16,1,2,32,14,105,21,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412332,412332,413915,4,0,0,23,7,3,5,0,0,11,4,2,11,0,7,False
412333,412333,413916,1,1,1,11,3,19,8,0,0,5,11,2,10,4,10,False
412334,412334,413917,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,False
412335,412335,413918,0,0,0,0,1,5,1,0,1,0,0,0,0,0,1,True
412336,412336,413919,1,1,0,6,0,5,0,0,0,1,3,0,10,0,5,False

In [4]:


# For convinience, divide the dataframe cc based on two labels. 

nor_obs = normal_documents.loc[normal_documents.labeled==False]    #Data frame with normal observation
ano_obs = normal_documents.loc[normal_documents.labeled==True]    #Data frame with anomalous observation

In [5]:
nor_obs

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False
1,1,1,0,0,0,2,0,0,0,0,0,22,0,1,1,0,0,False
2,2,2,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,False
3,3,3,2,1,0,2,1,4,3,0,1,3,1,0,0,1,1,False
4,4,4,1,17,1,40,7,4,16,1,2,32,14,105,21,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412331,412331,413914,0,0,0,0,0,1,1,0,0,0,0,0,0,3,1,False
412332,412332,413915,4,0,0,23,7,3,5,0,0,11,4,2,11,0,7,False
412333,412333,413916,1,1,1,11,3,19,8,0,0,5,11,2,10,4,10,False
412334,412334,413917,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,False
412336,412336,413919,1,1,0,6,0,5,0,0,0,1,3,0,10,0,5,False

In [6]:
ano_obs

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
302,302,302,2,0,0,1,0,0,1,0,0,2,1,1,1,3,2,True
321,321,321,264,24,31,45,99,224,430,6,40,17,88,22,80,1246,323,True
375,375,375,0,0,3,16,0,0,8,2,0,26,9,4,10,1,2,True
437,437,438,0,0,1,0,1,4,1,0,1,0,0,0,0,0,1,True
938,938,941,1,1,0,5,0,4,0,0,0,0,0,0,0,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410729,410729,412305,0,1,0,1,0,0,0,0,0,1,0,2,2,0,0,True
411376,411376,412954,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,True
411805,411805,413384,0,5,1,2,2,1,2,0,2,1,3,1,1,0,0,True
412250,412250,413833,3,1,1,9,0,6,0,0,0,0,0,1,28,0,0,True
412335,412335,413918,0,0,0,0,1,5,1,0,1,0,0,0,0,0,1,True

In [7]:
total_documents = pd.read_csv('/home/nazma/NLP-based-Email-Content-Digital-Forensic-using-ML-model-and-Explainable-AI/merged_topic_features_labeled.csv')
total_documents

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False
1,1,1,0,0,0,2,0,0,0,0,0,22,0,1,1,0,0,False
2,2,2,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,False
3,3,3,2,1,0,2,1,4,3,0,1,3,1,0,0,1,1,False
4,4,4,1,17,1,40,7,4,16,1,2,32,14,105,21,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515659,103322,103476,0,0,0,3,0,0,1,0,0,1,1,0,0,0,0,False
515660,103323,103477,0,0,0,1,1,0,1,0,1,0,0,0,1,0,0,False
515661,103324,103478,0,3,0,1,0,8,1,0,0,2,4,2,0,0,3,False
515662,103325,103479,2,1,0,15,3,3,3,0,0,4,3,1,3,0,4,False
515663,103326,103480,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,False

In [9]:
# For convinience, divide the dataframe cc based on two labels. 

nor_obs = total_documents.loc[total_documents.labeled==False]    #Data frame with normal observation
ano_obs = total_documents.loc[total_documents.labeled==True]    #Data frame with anomalous observation

In [10]:
nor_obs

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False
1,1,1,0,0,0,2,0,0,0,0,0,22,0,1,1,0,0,False
2,2,2,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,False
3,3,3,2,1,0,2,1,4,3,0,1,3,1,0,0,1,1,False
4,4,4,1,17,1,40,7,4,16,1,2,32,14,105,21,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515659,103322,103476,0,0,0,3,0,0,1,0,0,1,1,0,0,0,0,False
515660,103323,103477,0,0,0,1,1,0,1,0,1,0,0,0,1,0,0,False
515661,103324,103478,0,3,0,1,0,8,1,0,0,2,4,2,0,0,3,False
515662,103325,103479,2,1,0,15,3,3,3,0,0,4,3,1,3,0,4,False
515663,103326,103480,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,False

In [11]:
ano_obs

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14,labeled
302,302,302,2,0,0,1,0,0,1,0,0,2,1,1,1,3,2,True
321,321,321,264,24,31,45,99,224,430,6,40,17,88,22,80,1246,323,True
375,375,375,0,0,3,16,0,0,8,2,0,26,9,4,10,1,2,True
437,437,438,0,0,1,0,1,4,1,0,1,0,0,0,0,0,1,True
938,938,941,1,1,0,5,0,4,0,0,0,0,0,0,0,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514526,102189,102342,0,0,0,3,0,0,1,0,0,3,1,2,3,0,0,True
514615,102278,102431,0,2,0,7,1,2,5,0,0,5,4,4,4,1,3,True
514621,102284,102437,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,True
514683,102346,102499,0,0,0,2,0,0,0,0,0,2,0,1,4,0,0,True
515392,103055,103209,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,True

In [13]:


# Once class SVM is trained with the observations of only one class. In this case, the algorithm is trained with 
# first 200,000 observation of normal transactions. The remaining observation is merged with the anomalous observation 
# to create a test set. 

train_feature = nor_obs.loc[0:200000, :]
train_feature = train_feature.drop('labeled', axis=1)
Y_1 = nor_obs.loc[200000:, 'labeled']
Y_2 = ano_obs['labeled']

In [15]:
# Creating test observations/features

X_test_1 = nor_obs.loc[200000:, :].drop('labeled',axis=1)
X_test_2 = ano_obs.drop('labeled',axis=1)
# X_test = X_test_1.append(X_test_2)
X_test = pd.concat([X_test_1, X_test_2], ignore_index=True)

In [16]:
X_test

,Unnamed: 0,doc_id,topic 0,topic 1,topic 2,topic 3,topic 4,topic 5,topic 6,topic 7,topic 8,topic 9,topic 10,topic 11,topic 12,topic 13,topic 14
0,200000,200796,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,200001,200797,0,0,0,2,0,4,0,0,0,2,2,1,4,0,3
2,200002,200798,0,0,0,6,0,1,3,0,0,10,7,3,3,0,0
3,200003,200799,2,0,0,1,3,1,8,0,0,1,7,0,1,5,6
4,200004,200800,0,2,0,0,1,10,2,0,0,1,4,0,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315197,102189,102342,0,0,0,3,0,0,1,0,0,3,1,2,3,0,0
315198,102278,102431,0,2,0,7,1,2,5,0,0,5,4,4,4,1,3
315199,102284,102437,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
315200,102346,102499,0,0,0,2,0,0,0,0,0,2,0,1,4,0,0
315201,103055,103209,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [20]:

from sklearn import svm

# Setting the hyperparameters for Once Class SVM

oneclass = svm.OneClassSVM(kernel='linear', gamma=0.001, nu=0.95)

# I have used various combination of hyperparameters like linear, rbf, poly, gamma- 0.001, 0.0001, nu- 0.25, 0.5, 0.75, 0.95
# This combination gave me the most satisfactory results.# The remain data set is (after 200,000 observations) are appended with anomalous observations

Y_1 = nor_obs.loc[200000:, 'labeled']
Y_2 = ano_obs['labeled']

# Y_test= Y_1.append(Y_2)
Y_test = pd.concat([Y_1, Y_2], ignore_index=True)

#Y_test is used to evaluate the model

In [21]:
# Training the algorithm with the features. 
# This stage is very time consuming processes.

oneclass.fit(train_feature)

OneClassSVM(gamma=0.001, kernel='linear', nu=0.95)

In [22]:


# Test the algorithm on the test set

fraud_pred = oneclass.predict(X_test)

In [23]:
import numpy as np
# Check the number of outliers predicted by the algorithm

unique, counts = np.unique(fraud_pred, return_counts=True)
print (np.asarray((unique, counts)).T)

[[    -1 103613]
 [     1 211589]]

In [24]:


#Convert Y-test and fraud_pred to dataframe for ease of operation

Y_test= Y_test.to_frame()
Y_test=Y_test.reset_index()
fraud_pred = pd.DataFrame(fraud_pred)
fraud_pred= fraud_pred.rename(columns={0: 'prediction'})

In [25]:
##Performance check of the model

TP = FN = FP = TN = 0
for j in range(len(Y_test)):
    if Y_test['labeled'][j]== False and fraud_pred['prediction'][j] == 1:
        TP = TP+1
    elif Y_test['labeled'][j]== False and fraud_pred['prediction'][j] == -1:
        FN = FN+1
    elif Y_test['labeled'][j]== True and fraud_pred['prediction'][j] == 1:
        FP = FP+1
    else:
        TN = TN +1
print (TP,  FN,  FP,  TN)

210888 102557 701 1056

In [29]:


# Performance Matrix

accuracy = (TP+TN)/(TP+FN+FP+TN)
print (accuracy)
precision = TP/(TP + FP)
print(precision)
recall = TP/(TP + FN)
print(recall)
f1_score = (2 * precision * recall) / (precision + recall)
print(f1_score)
sensitivity = TP/(TP+FN)
print (sensitivity)
specificity = TN/(TN+FP)
print (specificity)

0.6724069009714405
0.9966869733303716
0.6728070315366332
0.8033308319080289
0.6728070315366332
0.6010244735344337