In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
enron_emails = pd.read_csv('~/Downloads/enron_05_17_2015_with_labels_v2.csv')

/tmp/ipykernel_12453/4237214209.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  enron_emails = pd.read_csv('~/Downloads/enron_05_17_2015_with_labels_v2.csv')

In [3]:
enron_emails

,Unnamed: 0,Message-ID,Date,From,To,Subject,X-From,X-To,X-cc,X-bcc,...,Cat_10_level_1,Cat_10_level_2,Cat_10_weight,Cat_11_level_1,Cat_11_level_2,Cat_11_weight,Cat_12_level_1,Cat_12_level_2,Cat_12_weight,labeled
0,0,<18782981.1075855378110.JavaMail.evans@thyme>,2001-05-14 23:39:00,frozenset({'phillip.allen@enron.com'}),frozenset({'tim.belden@enron.com'}),NaN,Phillip K Allen,Tim Belden <Tim Belden/Enron@EnronXGate>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1,<15464986.1075855378456.JavaMail.evans@thyme>,2001-05-04 20:51:00,frozenset({'phillip.allen@enron.com'}),frozenset({'john.lavorato@enron.com'}),Re:,Phillip K Allen,John J Lavorato <John J Lavorato/ENRON@enronXg...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,2,<24216240.1075855687451.JavaMail.evans@thyme>,2000-10-18 10:00:00,frozenset({'phillip.allen@enron.com'}),frozenset({'leah.arsdall@enron.com'}),Re: test,Phillip K Allen,Leah Van Arsdall,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,3,<13505866.1075863688222.JavaMail.evans@thyme>,2000-10-23 13:13:00,frozenset({'phillip.allen@enron.com'}),frozenset({'randall.gay@enron.com'}),NaN,Phillip K Allen,Randall L Gay,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,4,<30922949.1075863688243.JavaMail.evans@thyme>,2000-08-31 12:07:00,frozenset({'phillip.allen@enron.com'}),frozenset({'greg.piper@enron.com'}),Re: Hello,Phillip K Allen,Greg Piper,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517396,517396,<26807948.1075842029936.JavaMail.evans@thyme>,2001-11-28 21:30:11,frozenset({'john.zufferli@enron.com'}),frozenset({'kori.loibl@enron.com'}),Trade with John Lavorato,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Loibl, Kori </O=ENRON/OU=NA/CN=RECIPIENTS/CN=K...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
517397,517397,<25835861.1075842029959.JavaMail.evans@thyme>,2001-11-28 20:47:48,frozenset({'john.zufferli@enron.com'}),frozenset({'john.lavorato@enron.com'}),Gas Hedges,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Lavorato, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
517398,517398,<28979867.1075842029988.JavaMail.evans@thyme>,2001-11-28 15:20:00,frozenset({'john.zufferli@enron.com'}),frozenset({'dawn.doucet@enron.com'}),RE: CONFIDENTIAL,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Doucet, Dawn </O=ENRON/OU=NA/CN=RECIPIENTS/CN=...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
517399,517399,<22052556.1075842030013.JavaMail.evans@thyme>,2001-11-27 19:52:45,frozenset({'john.zufferli@enron.com'}),frozenset({'jeanie.slone@enron.com'}),Calgary Analyst/Associate,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...","Slone, Jeanie </O=ENRON/OU=NA/CN=RECIPIENTS/CN...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
517400,517400,<28618979.1075842030037.JavaMail.evans@thyme>,2001-11-26 18:48:43,frozenset({'john.zufferli@enron.com'}),frozenset({'livia_zufferli@monitor.com'}),RE: ali's essays,"Zufferli, John </O=ENRON/OU=NA/CN=RECIPIENTS/C...",'Livia_Zufferli@Monitor.com@ENRON',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [4]:
selected_features = ["Message-ID", "Date", "From", "To", "Subject", "X-From", "X-To","content"]
X = enron_emails[selected_features]
X_train, X_test, y_train, y_test = train_test_split(X, enron_emails["labeled"], test_size=0.2, random_state=42)  # Replace "content" with feature name and "target" if applicable
X_train

,Message-ID,Date,From,To,Subject,X-From,X-To,content
461188,<20350268.1075857438942.JavaMail.evans@thyme>,2000-07-10 12:05:00,frozenset({'fletcher.sturm@enron.com'}),frozenset({'felix.buitron@enron.com'}),Re: Memory,Fletcher J Sturm,Felix Buitron,anytime after 4:30pm is fine...I am at EB-3233...
188056,<19748462.1075846933395.JavaMail.evans@thyme>,2000-03-10 08:47:00,frozenset({'tana.jones@enron.com'}),"frozenset({'alan.aronowitz@enron.com', 'harry....",EOL Credit Responses 3/9,Tana Jones,"Alan Aronowitz, Jeffrey T Hodge, Stacy E Dicks...",---------------------- Forwarded by Tana Jones...
475897,<769685.1075859890053.JavaMail.evans@thyme>,1999-08-05 16:51:00,frozenset({'mark.taylor@enron.com'}),frozenset({'andrew.thomas@enron.com'}),Re: Long Sentences,Mark - ECT Legal Taylor,Andrew Thomas,Thanks for the update - I can't say I'm too so...
407113,<12936065.1075863643173.JavaMail.evans@thyme>,2000-04-08 11:54:00,frozenset({'susan.scott@enron.com'}),"frozenset({'colleen.raker@enron.com', 'bret.re...",question,Susan Scott,"Louis Soldano, Bret Reich, Philip Crowley, Col...",I hated to e-mail all of you but I honestly do...
316932,<31294522.1075845896803.JavaMail.evans@thyme>,2001-06-07 16:54:00,frozenset({'enron.announcements@enron.com'}),frozenset({'houston.report@enron.com'}),Weekend Outage Report for 6-8-01 through 6-11-01,Enron Announcements,Houston Outage Report,------------------------ W E E K E N D S Y S T...
...,...,...,...,...,...,...,...,...
259178,<18051711.1075840881312.JavaMail.evans@thyme>,2002-02-04 15:02:05,frozenset({'david.oxley@enron.com'}),frozenset({'louise.kitchen@enron.com'}),FW: Fw: I know its annoying but,"Oxley, David </O=ENRON/OU=NA/CN=RECIPIENTS/CN=...","Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/...",Did you do all this over weekend? -----Origina...
365838,<30145653.1075854837828.JavaMail.evans@thyme>,2001-09-05 23:45:24,frozenset({'m..presto@enron.com'}),"frozenset({'harry.arora@enron.com', 'jim.meyn@...",FW: Generation Asset Valuation,"Presto, Kevin M. </O=ENRON/OU=NA/CN=RECIPIENTS...","Arora, Harry </O=ENRON/OU=NA/CN=RECIPIENTS/CN=...",Any interest in attending? -----Original Messa...
131932,<8145314.1075845150150.JavaMail.evans@thyme>,2001-04-19 18:24:00,frozenset({'chris.germany@enron.com'}),frozenset({'scott.neal@enron.com'}),EOL,Chris Germany,Scott Neal <Scott Neal/HOU/ECT@ECT>,"Please give Judy Townsend, Scott Goodell, and ..."
146867,<27072313.1075840580998.JavaMail.evans@thyme>,2001-04-30 22:22:00,frozenset({'lillahmay@aol.com'}),"frozenset({'ryanb@gosfgiants.com', 'karl12343@...",party,LillahMay@aol.com,"alex3325@yahoo.com, ryanb@gosfgiants.com, mark...",Greetings everyone. I just wanted to thank all...
121958,<15294201.1075859030603.JavaMail.evans@thyme>,2001-10-19 02:15:32,frozenset({'exchange.administrator@enron.com'}),frozenset({'mary.trosper@enron.com'}),Undeliverable: FW: 2002 Plan Lay Presentation ...,Exchange System Administrator <.>,"Trosper, Mary </O=ENRON/OU=NA/CN=RECIPIENTS/CN...",--------- Inline attachment follows --------- ...

In [10]:
X_train.to_csv('~/Desktop/training_data.csv')

In [5]:
Basic=[]

In [6]:
X_train = X_train.reset_index(drop=True)  # Reset to consecutive integers

In [7]:
X_train = pd.DataFrame(X_train)
Basic = X_train.content.apply(lambda t : t.lower() if type(t) is str else 'empty')

In [8]:
X_train["content"]

0         anytime after 4:30pm is fine...I am at EB-3233...
1         ---------------------- Forwarded by Tana Jones...
2         Thanks for the update - I can't say I'm too so...
3         I hated to e-mail all of you but I honestly do...
4         ------------------------ W E E K E N D S Y S T...
                                ...
413915    Did you do all this over weekend? -----Origina...
413916    Any interest in attending? -----Original Messa...
413917    Please give Judy Townsend, Scott Goodell, and ...
413918    Greetings everyone. I just wanted to thank all...
413919    --------- Inline attachment follows --------- ...
Name: content, Length: 413920, dtype: object

In [9]:
Basic

0         anytime after 4:30pm is fine...i am at eb-3233...
1         ---------------------- forwarded by tana jones...
2         thanks for the update - i can't say i'm too so...
3         i hated to e-mail all of you but i honestly do...
4         ------------------------ w e e k e n d s y s t...
                                ...
413915    did you do all this over weekend? -----origina...
413916    any interest in attending? -----original messa...
413917    please give judy townsend, scott goodell, and ...
413918    greetings everyone. i just wanted to thank all...
413919    --------- inline attachment follows --------- ...
Name: content, Length: 413920, dtype: object

In [16]:
import re
import nltk
import string
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
stop_words = set(stopwords.words('english'))
custom_stopwords = ["forward","forwarded","sorry", "please", "message", "messages","reply", "email",
                    "re", "subject", "to", "cc", "bcc", ":", "dear", "thanks", "thank",
                    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n",
                    "o", "p", "q", "s", "t", "u", "v", "w", "x", "y", "z",
                    "up", "down", "north", "south", "east", "west", "over", "under", "near", "far",
                    "and", "but", "or", "nor", "yet", "so", "because", "etc",
                    "this", "that", "these","those", "here", "there", "all", "any", "some", "none", "such",
                   ]
all_stopwords = stop_words.union(custom_stopwords)

[nltk_data] Downloading package punkt to /home/nazma/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/nazma/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/nazma/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [17]:
# Dictionary of English Contractions
contractions_dict = { "ain't": "are not","'s":" is","aren't": "are not",
                     "can't": "cannot","can't've": "cannot have",
                     "'cause": "because","could've": "could have","couldn't": "could not",
                     "couldn't've": "could not have", "didn't": "did not","doesn't": "does not",
                     "don't": "do not","hadn't": "had not","hadn't've": "had not have",
                     "hasn't": "has not","haven't": "have not","he'd": "he would",
                     "he'd've": "he would have","he'll": "he will", "he'll've": "he will have",
                     "how'd": "how did","how'd'y": "how do you","how'll": "how will",
                     "I'd": "I would", "I'd've": "I would have","I'll": "I will",
                     "I'll've": "I will have","I'm": "I am","I've": "I have", "isn't": "is not",
                     "it'd": "it would","it'd've": "it would have","it'll": "it will",
                     "it'll've": "it will have", "let's": "let us","ma'am": "madam",
                     "mayn't": "may not","might've": "might have","mightn't": "might not",
                     "mightn't've": "might not have","must've": "must have","mustn't": "must not",
                     "mustn't've": "must not have", "needn't": "need not",
                     "needn't've": "need not have","o'clock": "of the clock","oughtn't": "ought not",
                     "oughtn't've": "ought not have","shan't": "shall not","sha'n't": "shall not",
                     "shan't've": "shall not have","she'd": "she would","she'd've": "she would have",
                     "she'll": "she will", "she'll've": "she will have","should've": "should have",
                     "shouldn't": "should not", "shouldn't've": "should not have","so've": "so have",
                     "that'd": "that would","that'd've": "that would have", "there'd": "there would",
                     "there'd've": "there would have", "they'd": "they would",
                     "they'd've": "they would have","they'll": "they will",
                     "they'll've": "they will have", "they're": "they are","they've": "they have",
                     "to've": "to have","wasn't": "was not","we'd": "we would",
                     "we'd've": "we would have","we'll": "we will","we'll've": "we will have",
                     "we're": "we are","we've": "we have", "weren't": "were not","what'll": "what will",
                     "what'll've": "what will have","what're": "what are", "what've": "what have",
                     "when've": "when have","where'd": "where did", "where've": "where have",
                     "who'll": "who will","who'll've": "who will have","who've": "who have",
                     "why've": "why have","will've": "will have","won't": "will not",
                     "won't've": "will not have", "would've": "would have","wouldn't": "would not",
                     "wouldn't've": "would not have","y'all": "you all", "y'all'd": "you all would",
                     "y'all'd've": "you all would have","y'all're": "you all are",
                     "y'all've": "you all have", "you'd": "you would","you'd've": "you would have",
                     "you'll": "you will","you'll've": "you will have", "you're": "you are",
                     "you've": "you have"}

# Regular expression for finding contractions
contractions_re=re.compile('(%s)' % '|'.join(contractions_dict.keys()))

# Function for expanding contractions
def expand_contractions(content,contractions_dict=contractions_dict):
    def replace(match):
        return contractions_dict[match.group(0)]
    return contractions_re.sub(replace, content)

# Expanding Contractions in the content data
Basic = Basic.apply(lambda x:expand_contractions(x))

In [18]:
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

def remove_emails(text):
    # Regular expression pattern to match email addresses
    pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    # Find the matched email addresses
    # matches = re.findall(pattern, text)
    # print the matched email for check
    # print(matches)
    # Replace email addresses with an empty string
    return re.sub(pattern, '', text)

def remove_stopwords(content):
    "Return the content after remvoing stopwords"
    content_tokens = word_tokenize(content)
    filtered_content = [word for word in content_tokens if not word in all_stopwords]
    return " ".join(filtered_content)

#remove emails
Basic = Basic.apply(remove_emails)

#removing stopwords
Basic = Basic.apply(remove_stopwords)

#removing Punctuations
Basic = Basic.apply(lambda x: re.sub('[%s]' % re.escape(string.punctuation), '', x))

#removing digits
Basic = Basic.apply(lambda x: re.sub('\w*\d\w*','', x))

In [19]:
Basic.to_csv('~/Desktop/basic_with_index.csv', index=True)  # Save with row index

In [23]:
Basic

0         anytime after 4:30pm is fine...i am at eb-3233...
1         ---------------------- forwarded by tana jones...
2         thanks for the update - i can't say i'm too so...
3         i hated to e-mail all of you but i honestly do...
4         ------------------------ w e e k e n d s y s t...
                                ...
413915    did you do all this over weekend? -----origina...
413916    any interest in attending? -----original messa...
413917    please give judy townsend, scott goodell, and ...
413918    greetings everyone. i just wanted to thank all...
413919    --------- inline attachment follows --------- ...
Name: content, Length: 413920, dtype: object

In [2]:
basic = pd.read_csv('~/Desktop/basic_with_index.csv')
basic

        Unnamed: 0                                            content
0                0                                anytime fine fletch
1                1  tana joneshouect molly harris pm frank davisho...
2                2  update say delay since spare moment look anywa...
3                3  hated honestly know handle attached thought on...
4                4  r june june ecs ecn network interconnection ju...
...            ...                                                ...
413915      413915  weekend original mailto sent monday february o...
413916      413916  interest attending original bean kenneth sent ...
413917      413917  give judy townsend scott goodell ability trade...
413918      413918  greetings everyone wanted coming housewarming ...
413919      413919  inline attachment follows trosper mary trosper...

[413920 rows x 2 columns]

In [23]:
X_train.content[3]

'I hated to e-mail all of you but I honestly do not know how to handle the attached which was forwarded to me, and thought one of you might. Any clues...please advise. Thanks. Lora Ellis@ECT 04/06/2000 10:59 AM To: Emily Sellers/ET&S/Enron@ENRON cc: Subject: Bond Renewals June 2000 The following bond will be expiring soon, please let me know if it is still needed or if it can be cancelled Transwestern Pipeline Company Bond No. JP 0914 $2500. Damage Bond/Right of Way or Water Lease To: State of New Mexico Cancellation Provision: None Renewal Date: 06-03-00 Thanks for your help.'

In [6]:
basic["content"]

0                                       anytime fine fletch
1         tana joneshouect molly harris pm frank davisho...
2         update say delay since spare moment look anywa...
3         hated honestly know handle attached thought on...
4         r june june ecs ecn network interconnection ju...
                                ...
413915    weekend original mailto sent monday february o...
413916    interest attending original bean kenneth sent ...
413917    give judy townsend scott goodell ability trade...
413918    greetings everyone wanted coming housewarming ...
413919    inline attachment follows trosper mary trosper...
Name: content, Length: 413920, dtype: object

In [21]:
X_train['processed_text']=basic["content"]

In [33]:
X_train
basic = pd.DataFrame(basic)
type(basic)
basic["content"]

0                                       anytime fine fletch
1         tana joneshouect molly harris pm frank davisho...
2         update say delay since spare moment look anywa...
3         hated honestly know handle attached thought on...
4         r june june ecs ecn network interconnection ju...
                                ...
413915    weekend original mailto sent monday february o...
413916    interest attending original bean kenneth sent ...
413917    give judy townsend scott goodell ability trade...
413918    greetings everyone wanted coming housewarming ...
413919    inline attachment follows trosper mary trosper...
Name: content, Length: 413920, dtype: object

In [3]:
from nltk.tokenize import word_tokenize

# def remove_extra_marks(content):
#     extra_keys = ["’","—","”","“"]
#     content_tokens = word_tokenize(content)
#     filtered_content = [word for word in content_tokens if not word in extra_keys]
#     return " ".join(filtered_content)
   
    
extra_marks = "".join(["’", "—", "”", "“"])  # Combine all extra marks into a single string
basic.content = basic["content"].str.replace(extra_marks, "", regex=True)

basic
# # X_print.processed_text = basic["content"].apply(remove_extra_marks)
# X_print.processed_text = basic["content"].str.replace(extra_keys, "", regex=True)

        Unnamed: 0                                            content
0                0                                anytime fine fletch
1                1  tana joneshouect molly harris pm frank davisho...
2                2  update say delay since spare moment look anywa...
3                3  hated honestly know handle attached thought on...
4                4  r june june ecs ecn network interconnection ju...
...            ...                                                ...
413915      413915  weekend original mailto sent monday february o...
413916      413916  interest attending original bean kenneth sent ...
413917      413917  give judy townsend scott goodell ability trade...
413918      413918  greetings everyone wanted coming housewarming ...
413919      413919  inline attachment follows trosper mary trosper...

[413920 rows x 2 columns]

In [4]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [7]:
def split_chunks(data, num_chunks):
  """Splits a list (or any iterable) into chunks of a specified size."""
  chunk_size = len(data) // num_chunks  # Integer division for equal chunks (rounded down)
  return [data[i:i + chunk_size] for i in range(0, len(data), chunk_size)]

num_chunks = 10

chunks = split_chunks(basic, num_chunks)
print(chunks)

[       Unnamed: 0                                            content
0               0                                anytime fine fletch
1               1  tana joneshouect molly harris pm frank davisho...
2               2  update say delay since spare moment look anywa...
3               3  hated honestly know handle attached thought on...
4               4  r june june ecs ecn network interconnection ju...
...           ...                                                ...
41387       41387  susan susan could one send notice concerning f...
41388       41388  jim since susan miss callmeeting vacationing m...
41389       41389  mike grigsbyhouect fw bobby knight cartoon jos...
41390       41390  report named powergas heat rates published ava...
41391       41391  diana heard back prebon wrong fixed deal let k...

[41392 rows x 2 columns],        Unnamed: 0                                            content
41392       41392  fyi jeffrey shankmanhouect christian lebroc en...
41393       41393  name new head generation kn anthony lannie for...
41394       41394  presentations san antonio leadership conferenc...
41395       41395                                      yes good idea
41396       41396  order bring better legal coordination standard...
...           ...                                                ...
82779       82779  ad hoc group electricity crisis assemblyman jo...
82780       82780  automatic confirmation order placed using cent...
82781       82781  question assume open means able trade without ...
82782       82782  registration harassment avoidance march cancel...
82783       82783  darla attached latest greatest crude deal spre...

[41392 rows x 2 columns],         Unnamed: 0                                            content
82784        82784  tim belden trading heather dunton risk john po...
82785        82785  april business use following ena contracts cga...
82786        82786  celeste would like ask favor would like sevil ...
82787        82787  hi susan hertz rental car voucher need later s...
82788        82788  managers supervisors participation contributio...
...            ...                                                ...
124171      124171  joe confirm site visit company gleason lincoln...
124172      124172  iso saying authority require epmi report price...
124173      124173  joe articles state deregulation better everyon...
124174      124174  original katherine thomas sent tuesday decembe...
124175      124175  administrative ehs performance targets ehs glo...

[41392 rows x 2 columns],         Unnamed: 0                                            content
124176      124176  gs co gsi different repo agreements generated ...
124177      124177  based discussions sally discussions ted rick c...
124178      124178  tana dow information access document attached ...
124179      124179  received listed security approver click approv...
124180      124180  order save twenty bucks purchase either games ...
...            ...                                                ...
165563      165563  writes nyisotechexchange discussion list marke...
165564      165564  scott congrats great tech analysis late called...
165565      165565  pennfuture ecubed commentary biweekly publicat...
165566      165566  charlie following spreadsheets contain physica...
165567      165567  alert posted december demand mismatch order no...

[41392 rows x 2 columns],         Unnamed: 0                                            content
165568      165568  respond mr campbell attached summary table sho...
165569      165569  agree original palmer lizzette sent tuesday no...
165570      165570        yes received note call soon get opportunity
165571      165571  leslie robinson enron pm susan pereirahouect e...
165572      165572  whoo hooo took demand charge calp may affects ...
...            ...                                                ...
206955      206955  aware enron utilizes temporary staffing servic...
206956      206956  hi jake rest went powell found one beautiful o...
206957      206957  fyi daren farmerhouect lisa kinsey alicia jone...
206958      206958  hi tana rex would like move sun nda using exac...
206959      206959  change storage model output total value versus...

[41392 rows x 2 columns],         Unnamed: 0                                            content
206960      206960  would like help take ownership project fully a...
206961      206961  glad hear read whole story hopefully true pl p...
206962      206962  kimberly oswald st fortuna ca mr ken lay writi...
206963      206963  hi john confirm amounts regard june payroll ex...
206964      206964  hi folks footballguy scott luebke takes look w...
...            ...                                                ...
248347      248347  following summary findings selecting risk syst...
248348      248348  yes killed checking kate melissa ann murphy ka...
248349      248349  vince minor revision earlier shown last line r...
248350      248350  attached summary two recent edison advice lett...
248351      248351  andrea computed hc historical volatility last ...

[41392 rows x 2 columns],         Unnamed: 0                                            content
248352      248352  reservation status changed received see attach...
248353      248353  congratz know long decision delayed best jeff ...
248354      248354                                                NaN
248355      248355  enron managing directors vice presidents direc...
248356      248356  theresa villeggiante administrative assistant ...
...            ...                                                ...
289739      289739  wednesday work best say daily review original ...
289740      289740  memo attempt give background work legal done l...
289741      289741  hey aunt bonnie thoroughly enjoyed visit well ...
289742      289742  great pictures great weekend ben original smtp...
289743      289743  phillip lovehouect pm phillip love scott wachs...

[41392 rows x 2 columns],         Unnamed: 0                                            content
289744      289744  mr love br br signing neteller fastest secure ...
289745      289745  mar asked eloan monitor mortgage market daily ...
289746      289746  rain like coordinate fellas hunter scott let u...
289747      289747  important little bird told candidates enron ex...
289748      289748  currently experiencing problem ability display...
...            ...                                                ...
331131      331131  answer michelle michelle cashhouect steve hami...
331132      331132  saw something intranet says check benefits inc...
331133      331133  note counterparty name change old name endesa ...
331134      331134  member happy holidays us prizeflowcom special ...
331135      331135  natural gas business continues benefit effecti...

[41392 rows x 2 columns],         Unnamed: 0                                            content
331136      331136  attached enron global markets eol crude violat...
331137      331137  helyette called home shall try office well num...
331138      331138  market participants assure notification respec...
331139      331139  could another interest rate decreases original...
331140      331140  http opinionjournalcom best web today november...
...            ...                                                ...
372523      372523  yes mark palmer enron steven kean ees james st...
372524      372524  original coulter kayne sent monday july gilber...
372525      372525  problems online rsvp form solved inconvenience...
372526      372526  nick plan happy comment item think also could ...
372527      372527  bad buy infinity miles major problems maybe jo...

[41392 rows x 2 columns],         Unnamed: 0                                            content
372528      372528  long short contact name list sounds like confi...
372529      372529  yes alexandra saler ees pm jeffrey shankmanhou...
372530      372530  steve richard spoke bob hansen yesterday get s...
372531      372531  fyi kay manncorpenron pm kay mann pm sheila tw...
372532      372532  suzanne savings bond program enron sponsors ye...
...            ...                                                ...
413915      413915  weekend original mailto sent monday february o...
413916      413916  interest attending original bean kenneth sent ...
413917      413917  give judy townsend scott goodell ability trade...
413918      413918  greetings everyone wanted coming housewarming ...
413919      413919  inline attachment follows trosper mary trosper...

[41392 rows x 2 columns]]

In [13]:
def lemmatize_text(text):

    if isinstance(text, str):
        doc = nlp(text)
        lemmatized_text = " ".join([token.lemma_ for token in doc])
        return lemmatized_text
    else:
        return ""  # Handle non-string elements (e.g., return empty string)

"""# Split train_data into chunks
chunk_size = int(len(basic) / 10)  # Calculate chunk size for 10 chunks
chunks = [basic[i:i + chunk_size] for i in range(0, len(basic), chunk_size)]
"""


# Lemmatize chunks and update original DataFrame
for i, chunk in enumerate(chunks):
  lemmatized_chunk = chunk["content"].apply(lemmatize_text)
  basic.loc[chunk.index, "content"] = lemmatized_chunk
    


# # Lemmatize each chunk
# for i, chunk in enumerate(chunks):
# #   chunk['lemmatized_content'] = chunk['content'].apply(lemmatize_text)
#   chunk.loc[:, 'lemmatized_content'] = chunk['content'].apply(lemmatize_text)
# #   chunk['lemmatized_content'] = chunk['lemmatized_content'].set_index(range(i*chunk_size, (i+1)*chunk_size))
#   # Update the corresponding chunk in train_data using .loc (fixing the warning)
#   X_train.loc[i*chunk_size: (i+1)*chunk_size-1, 'lemmatized_content'] = chunk['lemmatized_content']

# # Alternatively, create a new DataFrame with all chunks (Option 2)
# # new_train_data = pd.concat(chunks, ignore_index=True)

# X_train  # Print the modified train_data (with "lemmatized_content" column)

'\n\n# Lemmatize each chunk\nfor i, chunk in enumerate(chunks):\n#   chunk[\'lemmatized_content\'] = chunk[\'content\'].apply(lemmatize_text)\n  chunk.loc[:, \'lemmatized_content\'] = chunk[\'content\'].apply(lemmatize_text)\n#   chunk[\'lemmatized_content\'] = chunk[\'lemmatized_content\'].set_index(range(i*chunk_size, (i+1)*chunk_size))\n  # Update the corresponding chunk in train_data using .loc (fixing the warning)\n  X_train.loc[i*chunk_size: (i+1)*chunk_size-1, \'lemmatized_content\'] = chunk[\'lemmatized_content\']\n\n# Alternatively, create a new DataFrame with all chunks (Option 2)\n# new_train_data = pd.concat(chunks, ignore_index=True)\n\nX_train  # Print the modified train_data (with "lemmatized_content" column)\n'

In [14]:
basic.to_csv('~/Desktop/basic_lemmatized_content.csv', index=True)  # Save with row index

In [15]:
import wordcloud
from wordcloud import WordCloud

#combine all the contents
content_data = ""
for text in basic.content:
    content_data = content_data+" "+text

#ploting the word cloud
plt.figure(figsize=(10, 10))
wordcloud = WordCloud(width = 500, height = 500, background_color='#40E0D0', colormap="ocean",  random_state=10).generate(content_data)
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

KeyboardInterrupt:

In [2]:
basic = pd.read_csv('~/Desktop/basic_lemmatized_content.csv')
basic

,Unnamed: 0.1,Unnamed: 0,content
0,0,0,anytime fine fletch
1,1,1,tana joneshouect molly harris pm frank davisho...
2,2,2,update say delay since spare moment look anywa...
3,3,3,hate honestly know handle attach think one mig...
4,4,4,r june june ecs ecn network interconnection ju...
...,...,...,...
413915,413915,413915,weekend original mailto send monday february o...
413916,413916,413916,interest attend original bean kenneth send wed...
413917,413917,413917,give judy townsend scott goodell ability trade...
413918,413918,413918,greeting everyone want come housewarme party m...
413919,413919,413919,inline attachment follow trosper mary trosper ...